services:
  rag_backend:
    build:
      context: ./backend
    volumes:
      - ./backend/chroma_db:/backend/chroma_db
      - ./data:/backend/data
    ports:
      - "8000:8000"
    env_file:
      - .env

  rag_frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
