version: "3.9"

services:
  rag_backend:
    build:
      context: ./backend
    container_name: rag_backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    command: uvicorn main:backend --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    restart: always

  rag_frontend:
    build:
      context: ./frontend
    container_name: rag_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    tty: true
    restart: always
